/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_GetThreadID */

#ifndef _Included_jni_GetThreadID
#define _Included_jni_GetThreadID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_GetThreadID
 * Method:    get_tid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_GetThreadID_get_1tid
  (JNIEnv *, jclass);

/*
 * Class:     jni_GetThreadID
 * Method:    setAffinity
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jni_GetThreadID_setAffinity
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
